language: ruby
cache: bundler
sudo: required
before_script:
- bundle exec thor setup:dev_env
- bundle exec rake db:setup db:migrate
script:
- bundle exec rake
- bundle exec rubocop
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq fontconfig libxrender1
- wget http://download.gna.org/wkhtmltopdf/0.12/0.12.1/wkhtmltox-0.12.1_linux-precise-amd64.deb
- sudo dpkg -i wkhtmltox-0.12.1_linux-precise-amd64.deb
deploy:
  provider: heroku
  api_key:
    secure: aIAoG592OjeAamb+QVOqfpt0hAPrasyKc30/4fNXtvNBpRH00nOFVmh0EWI7bppkV10a7ANVVPyx+4qBfgA01DzGzr4E6zfd2vhq4aGan6Czb5rOSjlkGs9bdMITHV0QY3a77qcPHuYNIlXxajX4KgN+g2G750b+lpZkqnv/9lY=
  on: master
  app: reckoningio
  run:
  - rake db:migrate
  - restart
